<?php

namespace AbCreative\LaravelMaker\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

class BuildCleanCommand extends BaseCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'build:clean {file : The name of the definition file in /databases/models/ e.g. posts.yaml} {--force=true} {--clean=true}';

    /**
     * The filesystem instance.
     *
     * @var \Illuminate\Filesystem\Filesystem
     */
    public $filesystem;

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete all the files generated by the package';

    /**
     * The resource_types to run...
     *
     * @var array
     */
    protected $resource_types = [

        'Migration',
        'Controller',
        'Template',
        'Model',
        'Request',
        'View',
        'Route',

    ];
}
